# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-19 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.png', upload_to='app01/avatar/', verbose_name='默认头像'),
        ),
    ]
