# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-12-20 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20211219_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '文章和标签关系表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '个人站点表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '文章分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '文章标签表'},
        ),
        migrations.AlterModelOptions(
            name='upanddown',
            options={'verbose_name_plural': '点赞点踩表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
